# Numpy 101

The goal of this challenge is to get familiar with the Numpy library, manipulate multidimensional arrays and apply some linear algebra operations without using `for` loops.

💡 Do not forget to keep the [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) closed during this challenge.

In [1]:
import numpy as np # Run this cell!

---

**Q1** - Create a null vector (i.e. with only zeros `0`) of size 10 and assign it to a variable named `ten_zeros`. 

It should look like this:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [2]:
# YOUR CODE HERE
ten_zeros = np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

**Q2** - Create a vector with values from 5 to 10 and assign it to a variable named `five_to_ten`.

It should look like this:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [15]:
# YOUR CODE HERE
five_to_ten = np.arange(5, 18)
five_to_ten

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

---

**Q3** - Create the following matrix as a NumPy `ndarray` and assign it to a variable named `A`:

$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and numpy.ndarray</code></a></p>
</details>

In [4]:
# YOUR CODE HERE
A = np.array([[5, 9, 7], [1, 0, 3]])
A

array([[5, 9, 7],
       [1, 0, 3]])

---
**Q4** - Create the following matrix without using the `np.array()` constructor and assign it to a variable named `B`:

$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [5]:
# YOUR CODE HERE
B = np.ones((2, 2), dtype=int)
B

array([[1, 1],
       [1, 1]])

---

**Q5** - Create a vector of 20 elements evenly spaced between `-1` and `1` and assign it to a variable named `lin_twenty`.

It should look like this:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [6]:
# YOUR CODE HERE
lin_twenty = np.linspace(-1, 1, 20)
lin_twenty

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

---

**Q6** - Create a 3x3 identity matrix and assign it to a variable named `C`:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [7]:
# YOUR CODE HERE
C = np.eye(3, dtype="int")
C

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

---

**Q7** - Create the following `ndarray` and assign it to a variable named `D`:  

$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$

Reshape `D` into a 2x3 matrix and assign it to a variable named `E`:

$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [8]:
# YOUR CODE HERE
D = np.array([2, 9, 7, 3, 1, 5])
E = D.reshape(2, 3)
E

array([[2, 9, 7],
       [3, 1, 5]])

---

**Q8** - Create a 8x8 checkboard matrix and assign it to a variable named `F`:

$
F = 
\begin{pmatrix}
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.tile.html"><code>numpy.tile</code></a></p>
</details>

In [9]:
# YOUR CODE HERE
F = np.tile(np.array([[1,0],[0,1]]), (4, 4))
F

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

---

**Q9**: Select the second column of this `ndarray` `G`, reshape it as an `ndarray` of 4 lines and 1 column and assign it to a variable named `reshaped_G`:

$
reshaped\_G = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [10]:
G = np.random.random((4, 5))
print(G)

[[0.20562331 0.05970629 0.50991086 0.64041805 0.77778171]
 [0.064648   0.95777754 0.92087727 0.64262188 0.61569844]
 [0.25978277 0.40362922 0.29343477 0.24310432 0.77034323]
 [0.9683476  0.79137457 0.05634196 0.21412943 0.02391802]]


In [11]:
# YOUR CODE HERE
reshaped_G = G[:, 1].reshape(4, 1)
reshaped_G

array([[0.05970629],
       [0.95777754],
       [0.40362922],
       [0.79137457]])

---

**Q10** - Compute the sum of matrixes `H` and `I` and store the result into a variable `hi_sum`:

$
H = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
I =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
H + I = ?
$


In [12]:
# Here we demonstrate two different approaches to creating a (3,2) Matrix
H = np.array([0, 4, -4, -3, 1, 1]).reshape(3, 2)
print('H: \n', H)
I = np.array([[0, 1], [1, -1], [2, 3]])
print('I: \n', I)

H: 
 [[ 0  4]
 [-4 -3]
 [ 1  1]]
I: 
 [[ 0  1]
 [ 1 -1]
 [ 2  3]]


In [13]:
# YOUR CODE HERE
hi_sum = H + I
hi_sum

array([[ 0,  5],
       [-3, -4],
       [ 3,  4]])

## Check your code!

Run the cell below to check your code:

In [19]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_G=reshaped_G,
    hi_sum=hi_sum
)
result.write()
print(result.check())

In [18]:
!make

find . -iname "*.py" -not -path "./tests/*" | xargs -n1 -I {}  pylint --output-format=colorized {}; true
PYTHONDONTWRITEBYTECODE=1 pytest -v --color=yes


Access denied - .
File not found - -INAME
File not found - -NOT
File not found - -PATH
File not found - INIT.PY
File not found - NUMPY.PICKLE
File not found - TEST_NUMPY.PY
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
'PYTHONDONTWRITEBYTECODE' is not recognized as an internal or external command,
operable program or batch file.
make: *** [Makefile:7: pytest] Error 1
